service:
  type: NodePort
  nodePort: 31209

ingress:
  enabled: false

db:
  type: postgresdb

postgresql:
  enabled: false

# 外接 PostgreSQL（生产推荐）
postgresdb:
  host: "CHANGE_ME"
  port: 5432
  database: n8n
  user: n8n
  password: "CHANGE_ME"

n8n:
  extraEnv:
    TZ: Asia/Shanghai
    N8N_PROTOCOL: http
    N8N_SECURE_COOKIE: "false"
    N8N_DIAGNOSTICS_ENABLED: "false"
    N8N_PERSONALIZATION_ENABLED: "false"
